<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitGallery
{
    public static $prefixLengthsPsr4 = array (
        'O' =>
        array (
            'OCA\\Gallery\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Gallery\\' =>
        array (
            0 => __DIR__ . '/../..' . '/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\Gallery\\AppInfo\\Application' => __DIR__ . '/../..' . '/lib/AppInfo/Application.php',
        'OCA\\Gallery\\Controller\\ApiController' => __DIR__ . '/../..' . '/lib/Controller/ApiController.php',
        'OCA\\Gallery\\Controller\\PageController' => __DIR__ . '/../..' . '/lib/Controller/PageController.php',
        'OCA\\Gallery\\Service\\AlbumService' => __DIR__ . '/../..' . '/lib/Service/AlbumService.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitGallery::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitGallery::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitGallery::$classMap;

        }, null, ClassLoader::class);
    }
}
