<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'OCA\\Gallery\\AppInfo\\Application' => $baseDir . '/lib/AppInfo/Application.php',
    'OCA\\Gallery\\Controller\\ApiController' => $baseDir . '/lib/Controller/ApiController.php',
    'OCA\\Gallery\\Controller\\PageController' => $baseDir . '/lib/Controller/PageController.php',
    'OCA\\Gallery\\Service\\AlbumService' => $baseDir . '/lib/Service/AlbumService.php',
);
